codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 75%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 10%

ignore:
  - "out/test/**"
  - "src/test/**"
  - "**/*.test.ts"
  - "media/**"
  - "scripts/**"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
